site_logo: /assets/uploads/logo.png
site_logo_white: /assets/uploads/logo-white.png
social_details:
  twitter_link: https://twitter.com/
  facebook_link: https://facebook.com/
  instagram_link: https://instagram.com/
